import { Inter } from 'next/font/google'
import Menu from '@/components/Menu'
import Login from '@/components/Login'
import ReduxProvider from '@/redux/provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({
  weight: '400',
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <ReduxProvider>
          <div className={'relative mx-auto max-w-4xl h-screen bg-white pt-16'}>
            {children}
            <Header>
              <Menu />
              <Login />
            </Header>
            <Footer />
          </div>
          
          
        </ReduxProvider>
      </body>
    </html>
  )
}

function Header ({ children } : { children: React.ReactNode}) {
  return (
    <header className={'absolute top-0 inset-x-0 p-3 flex bg-white justify-between items-center'}>
      {children}
    </header>
  )
}

function Footer () {
  return (
    <footer className={'absolute bottom-0 inset-x-0 p-3'}>© 2023 paullai.dev. All rights reserved.</footer>
  )
}
